# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dateTime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dateTime.proto',
  package='demo.grpc',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x0e\x64\x61teTime.proto\x12\tdemo.grpc\"\x1c\n\x0b\x44\x61teTimeMsg\x12\r\n\x05value\x18\x01 \x01(\t2R\n\x08\x44\x61teTime\x12\x46\n\x12getCurrentDateTime\x12\x16.demo.grpc.DateTimeMsg\x1a\x16.demo.grpc.DateTimeMsg\"\x00\x42\x02P\x01\x62\x06proto3')
)




_DATETIMEMSG = _descriptor.Descriptor(
  name='DateTimeMsg',
  full_name='demo.grpc.DateTimeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='demo.grpc.DateTimeMsg.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['DateTimeMsg'] = _DATETIMEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DateTimeMsg = _reflection.GeneratedProtocolMessageType('DateTimeMsg', (_message.Message,), dict(
  DESCRIPTOR = _DATETIMEMSG,
  __module__ = 'dateTime_pb2'
  # @@protoc_insertion_point(class_scope:demo.grpc.DateTimeMsg)
  ))
_sym_db.RegisterMessage(DateTimeMsg)


DESCRIPTOR._options = None

_DATETIME = _descriptor.ServiceDescriptor(
  name='DateTime',
  full_name='demo.grpc.DateTime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=59,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCurrentDateTime',
    full_name='demo.grpc.DateTime.getCurrentDateTime',
    index=0,
    containing_service=None,
    input_type=_DATETIMEMSG,
    output_type=_DATETIMEMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATETIME)

DESCRIPTOR.services_by_name['DateTime'] = _DATETIME

# @@protoc_insertion_point(module_scope)
