# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dateTime_pb2 as dateTime__pb2


class DateTimeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCurrentDateTime = channel.unary_unary(
        '/demo.grpc.DateTime/getCurrentDateTime',
        request_serializer=dateTime__pb2.DateTimeMsg.SerializeToString,
        response_deserializer=dateTime__pb2.DateTimeMsg.FromString,
        )


class DateTimeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCurrentDateTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DateTimeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCurrentDateTime': grpc.unary_unary_rpc_method_handler(
          servicer.getCurrentDateTime,
          request_deserializer=dateTime__pb2.DateTimeMsg.FromString,
          response_serializer=dateTime__pb2.DateTimeMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.grpc.DateTime', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
